import type { Metadata } from "next";
import "../../styles/globals.css";
import { Header } from "@/app/[locale]/Header";
import { Providers } from "@/app/[locale]/providers";
import { Footer } from "@/app/[locale]/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}
export default function RootLayout({ children }: Props) {
  return (
    <html lang={"en"}>
      <body>
        {/*"use client" 컴포넌트는 Providers 컴포넌트 안에 있어야 합니다.*/}
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
